[package]
name = "yoga"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]

[dependencies]
libc = "0.2"
log = "0.4"
ordered-float = { version = "0.5", features = ["serde"] }
serde = "1"
serde_derive = "1"
